"""add listen_url and frustration_flagged to live_calls

Revision ID: 7fbc528c62a7
Revises: 0cbda9625217
Create Date: 2026-08-02 21:14:26.814554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fbc528c62a7'
down_revision: Union[str, Sequence[str], None] = '0cbda9625217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_calls', sa.Column('listen_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_calls', 'listen_url')
    # ### end Alembic commands ###
